package com.jadeguard.validation;

public enum ValidationErrorCode {
    UNSUPPORTED_CURRENCY,
    SAME_SENDER_AND_RECEIVER,
    INVALID_COUNTRY_CODE,
    ROUTE_REQUIRES_ORIGIN_AND_DESTINATION,
    INVALID_ROUTE_SEQUENCE,
    DUPLICATE_ROUTE_SEQUENCE
}
