import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";

import { ApiError } from "../api/ApiError";
import { getAuditEvents } from "../api/auditApi";
import { EmptyState } from "../components/feedback/EmptyState";
import { ErrorState } from "../components/feedback/ErrorState";
import { LoadingState } from "../components/feedback/LoadingState";
import type { AuditEventPage } from "../types/audit";

export function AuditListPage() {
  const [params, setParams] = useSearchParams(); const [result, setResult] = useState<AuditEventPage | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [draft, setDraft] = useState(() => ({ actorId: params.get("actorId") || "", action: params.get("action") || "", entityType: params.get("entityType") || "", entityId: params.get("entityId") || "" }));
  const page = Math.max(0, Number(params.get("page") || 0)); const size = Number(params.get("size") || 20);
  const load = useCallback(async () => { setLoading(true); try { setResult(await getAuditEvents({ actorId: params.get("actorId") || undefined, action: params.get("action") || undefined, entityType: params.get("entityType") || undefined, entityId: params.get("entityId") || undefined, page, size })); setError(""); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load audit events."); } finally { setLoading(false); } }, [params.toString()]);
  useEffect(() => { void load(); }, [load]);
  function apply(event: FormEvent) { event.preventDefault(); const next = new URLSearchParams(); Object.entries(draft).forEach(([key, value]) => { if (value.trim()) next.set(key, value.trim()); }); next.set("size", String(size)); setParams(next); }
  function move(nextPage: number) { const next = new URLSearchParams(params); next.set("page", String(nextPage)); setParams(next); }
  if (loading && !result) return <LoadingState message="Loading immutable audit history…" />;
  if (!result) return <ErrorState title="Audit history unavailable" message={error} onRetry={() => void load()} />;
  return <section className="audit-page"><div className="queue-toolbar"><div><p className="eyebrow">Governance and traceability</p><h2>Audit history</h2><p>Immutable user and system activity, newest first.</p></div><div className="audit-total"><strong>{result.totalElements}</strong><span>Total events</span></div></div><form className="alert-filters audit-filters" onSubmit={apply}><label>Actor ID<input value={draft.actorId} onChange={(event) => setDraft({ ...draft, actorId: event.target.value })} placeholder="User UUID or SYSTEM" /></label><label>Action<input value={draft.action} onChange={(event) => setDraft({ ...draft, action: event.target.value.toUpperCase() })} placeholder="ALERT_BLOCKED" /></label><label>Entity type<input value={draft.entityType} onChange={(event) => setDraft({ ...draft, entityType: event.target.value.toUpperCase() })} placeholder="ALERT" /></label><label className="transaction-search">Entity ID<input value={draft.entityId} onChange={(event) => setDraft({ ...draft, entityId: event.target.value })} placeholder="Entity UUID" /></label><label>Page size<select value={size} onChange={(event) => { const next = new URLSearchParams(params); next.set("size", event.target.value); next.set("page", "0"); setParams(next); }}><option>10</option><option>20</option><option>50</option><option>100</option></select></label><div className="filter-actions"><button className="primary-button compact-button">Apply filters</button><button type="button" className="clear-button" onClick={() => { setDraft({ actorId: "", action: "", entityType: "", entityId: "" }); setParams({ size: String(size) }); }}>Clear</button></div></form>{error && <div className="background-error">{error}</div>}{result.content.length === 0 ? <EmptyState title="No audit events match" description="Change or clear the selected filters." /> : <AuditTable events={result.content} />}<div className="pagination"><span>Page <strong>{result.page + 1}</strong> of <strong>{Math.max(result.totalPages, 1)}</strong></span><div><button disabled={result.page === 0 || loading} onClick={() => move(result.page - 1)}>← Previous</button><button disabled={result.page + 1 >= result.totalPages || loading} onClick={() => move(result.page + 1)}>Next →</button></div></div></section>;
}
function AuditTable({ events }: { events: AuditEventPage["content"] }) { return <div className="alert-table-card"><div className="alert-table-scroll"><table className="alert-table audit-table"><thead><tr><th>Occurred</th><th>Actor</th><th>Action</th><th>Entity</th><th>Reason</th><th /></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td data-label="Occurred"><time>{formatDate(event.occurredAt)}</time></td><td data-label="Actor"><strong>{event.actorUsername}</strong><code>{shortId(event.actorId)}</code></td><td data-label="Action"><span className="audit-action">{event.action}</span></td><td data-label="Entity"><strong>{event.entityType}</strong><code>{shortId(event.entityId)}</code></td><td data-label="Reason"><span className="reason-text">{event.reason || "No reason recorded"}</span></td><td><Link className="view-alert-link" to={`/admin/audit/${event.id}`}>Inspect →</Link></td></tr>)}</tbody></table></div></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value)); }
function shortId(value: string) { return value.length > 18 ? `${value.slice(0, 9)}…${value.slice(-5)}` : value; }
