import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";

import { ApiError } from "../api/ApiError";
import { getDashboardReports } from "../api/reportsApi";
import { DistributionChart } from "../components/dashboard/DistributionChart";
import { RankedBars } from "../components/dashboard/RankedBars";
import { VolumeChart } from "../components/dashboard/VolumeChart";
import { ErrorState } from "../components/feedback/ErrorState";
import { InlineSpinner } from "../components/feedback/InlineSpinner";
import { LoadingState } from "../components/feedback/LoadingState";
import type { RiskLevel } from "../components/badges/RiskBadge";
import type { DashboardReports, ReportFilters } from "../types/report";

const RISK_COLORS: Record<string, string> = { LOW: "#28c779", MEDIUM: "#f1b744", HIGH: "#ff8758", CRITICAL: "#ff5d78", PENDING: "#837b8a" };
const PRIORITY_COLORS: Record<string, string> = { HIGH: "#ff8758", CRITICAL: "#ff5d78" };

export function DashboardPage() {
  const [params, setParams] = useSearchParams(); const [data, setData] = useState<DashboardReports | null>(null);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const inFlight = useRef(false); const filters = filtersFrom(params);
  const load = useCallback(async (background = false) => { if (inFlight.current) return; inFlight.current = true; background ? setRefreshing(true) : setLoading(true); try { setData(await getDashboardReports(filters)); setError(""); setLastUpdated(new Date()); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load dashboard reports."); } finally { inFlight.current = false; setLoading(false); setRefreshing(false); } }, [params.toString()]);
  useEffect(() => { void load(false); }, [load]);
  useEffect(() => { const poll = () => { if (document.visibilityState === "visible") void load(true); }; const timer = window.setInterval(poll, 5000); document.addEventListener("visibilitychange", poll); return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", poll); }; }, [load]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next, { replace: true }); };
  if (loading && !data) return <LoadingState message="Building operations dashboard…" />;
  if (!data) return <ErrorState title="Dashboard unavailable" message={error || "Reporting data could not be loaded."} onRetry={() => void load(false)} />;
  const active = Object.entries(data.alerts.statusDistribution).filter(([status]) => status !== "CLOSED").reduce((sum, [, value]) => sum + value, 0);
  const open = data.alerts.statusDistribution.OPEN || 0; const amount = data.volume.reduce((sum, item) => sum + Number(item.totalAmount), 0);
  const riskItems = Object.entries(data.risk.riskDistribution).map(([label, value]) => ({ label, value, color: RISK_COLORS[label] || "#837b8a" }));
  const priorityItems = Object.entries(data.alerts.priorityDistribution).map(([label, value]) => ({ label, value, color: PRIORITY_COLORS[label] || "#a969ed" }));
  const countries = [...data.countries].sort((a, b) => b.averageRiskScore - a.averageRiskScore).slice(0, 7).map((item) => ({ key: item.countryCode, label: item.countryCode, value: Number(item.averageRiskScore), detail: `${item.transactionCount} transactions · ${item.alertCount} alerts` }));
  const rules = [...data.rules].sort((a, b) => b.triggerRate - a.triggerRate).slice(0, 7).map((item) => ({ key: item.ruleCode, label: item.ruleName, value: Number(item.triggerRate), detail: `${item.triggerCount}/${item.evaluationCount} triggered · +${item.totalScoreContribution} points` }));
  return <section className="operations-dashboard"><div className="queue-toolbar"><div><p className="eyebrow">Live monitoring</p><h2>Operations dashboard</h2><p>Risk, alerts and fund activity across JadeGuard.</p></div><div className="refresh-block">{refreshing && <InlineSpinner label="Refreshing" />}<span>Last successful refresh<br /><strong>{lastUpdated ? lastUpdated.toLocaleTimeString() : "Not yet"}</strong></span><button className="secondary-button" onClick={() => void load(true)} disabled={refreshing}>Refresh now</button></div></div><DashboardFilters params={params} update={update} clear={() => setParams({}, { replace: true })} />{error && <div className="background-error">Live refresh failed: {error}. The last successful dashboard remains visible.</div>}<div className="dashboard-kpis"><Kpi label="Transactions" value={data.risk.totalTransactions} detail={`${data.risk.highRiskTransactions} high risk`} tone="purple" /><Kpi label="Monitored amount" value={compactMoney(amount, filters.currency)} detail={`${data.volume.length} time periods`} tone="green" /><Kpi label="Average risk" value={Number(data.risk.averageRiskScore).toFixed(1)} detail="Across assessed transactions" tone="orange" /><Kpi label="Open alerts" value={open} detail={`${active} active workload`} tone="red" /></div><div className="dashboard-primary"><VolumeChart data={data.volume} /><DistributionChart eyebrow="Risk profile" title="Risk distribution" centerValue={data.risk.totalTransactions} items={riskItems} /></div><div className="dashboard-secondary"><DistributionChart eyebrow="Alert workload" title="Priority distribution" centerValue={data.alerts.totalAlerts} items={priorityItems} /><RankedBars eyebrow="Route intelligence" title="Highest-risk countries" items={countries} empty="No country-risk data" /><RankedBars eyebrow="Rule engine" title="Most effective rules" items={rules} empty="No rule evaluations" /></div></section>;
}

function DashboardFilters({ params, update, clear }: { params: URLSearchParams; update: (key: string, value: string) => void; clear: () => void }) { return <div className="alert-filters dashboard-filters"><label>From<input type="datetime-local" value={params.get("from") || ""} onChange={(event) => update("from", event.target.value)} /></label><label>To<input type="datetime-local" value={params.get("to") || ""} onChange={(event) => update("to", event.target.value)} /></label><label>Currency<input maxLength={3} value={params.get("currency") || ""} onChange={(event) => update("currency", event.target.value.toUpperCase())} placeholder="INR" /></label><label>Country<input maxLength={2} value={params.get("country") || ""} onChange={(event) => update("country", event.target.value.toUpperCase())} placeholder="IN" /></label><label>Risk<select value={params.get("riskLevel") || ""} onChange={(event) => update("riskLevel", event.target.value)}><option value="">All risks</option>{["PENDING", "LOW", "MEDIUM", "HIGH", "CRITICAL"].map((risk) => <option key={risk}>{risk}</option>)}</select></label><label>Volume interval<select value={params.get("interval") || "HOUR"} onChange={(event) => update("interval", event.target.value)}><option>HOUR</option><option>DAY</option></select></label><button className="clear-button" onClick={clear}>Clear filters</button></div>; }
function Kpi({ label, value, detail, tone }: { label: string; value: string | number; detail: string; tone: string }) { return <article className={`dashboard-kpi kpi-${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function filtersFrom(params: URLSearchParams): ReportFilters { return { from: params.get("from") || undefined, to: params.get("to") || undefined, currency: params.get("currency") || undefined, country: params.get("country") || undefined, riskLevel: (params.get("riskLevel") || undefined) as RiskLevel | undefined, interval: (params.get("interval") || "HOUR") as "HOUR" | "DAY" }; }
function compactMoney(value: number, currency?: string) { if (!currency) return new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(value); try { return new Intl.NumberFormat(undefined, { style: "currency", currency, notation: "compact", maximumFractionDigits: 1 }).format(value); } catch { return new Intl.NumberFormat(undefined, { notation: "compact", maximumFractionDigits: 1 }).format(value); } }
