import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";

import { ApiError } from "../api/ApiError";
import { downloadCsv, downloadPdf, getDashboardReports, type CsvReportType } from "../api/reportsApi";
import { DistributionChart } from "../components/dashboard/DistributionChart";
import { VolumeChart } from "../components/dashboard/VolumeChart";
import { ErrorState } from "../components/feedback/ErrorState";
import { LoadingState } from "../components/feedback/LoadingState";
import type { RiskLevel } from "../components/badges/RiskBadge";
import type { CountryRisk, DashboardReports, ReportFilters, RuleEffectiveness } from "../types/report";

const RISK_COLORS: Record<string, string> = { LOW: "#28c779", MEDIUM: "#f1b744", HIGH: "#ff8758", CRITICAL: "#ff5d78", PENDING: "#837b8a" };
const PRIORITY_COLORS: Record<string, string> = { HIGH: "#ff8758", CRITICAL: "#ff5d78" };
type Draft = { from: string; to: string; currency: string; country: string; riskLevel: string; interval: "HOUR" | "DAY" };

export function ReportsPage() {
  const [params, setParams] = useSearchParams(); const [data, setData] = useState<DashboardReports | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [generatedAt, setGeneratedAt] = useState<Date | null>(null); const [downloading, setDownloading] = useState("");
  const [draft, setDraft] = useState<Draft>(() => draftFrom(params)); const filters = filtersFrom(params);
  const load = useCallback(async () => { setLoading(true); try { setData(await getDashboardReports(filters)); setGeneratedAt(new Date()); setError(""); } catch (caught) { setError(messageOf(caught)); } finally { setLoading(false); } }, [params.toString()]);
  useEffect(() => { void load(); }, [load]);
  function generate(event: FormEvent) { event.preventDefault(); if (draft.from && draft.to && new Date(draft.from) >= new Date(draft.to)) { setError("The To date must be later than the From date."); return; } const next = new URLSearchParams(); Object.entries(draft).forEach(([key, value]) => { if (value && !(key === "interval" && value === "HOUR")) next.set(key, value); }); setParams(next); }
  async function exportFile(kind: "PDF" | CsvReportType) { setDownloading(kind); setError(""); try { const file = kind === "PDF" ? await downloadPdf(filters) : await downloadCsv(kind, filters); const url = URL.createObjectURL(file.blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = file.filename; anchor.click(); URL.revokeObjectURL(url); } catch (caught) { setError(messageOf(caught)); } finally { setDownloading(""); } }
  if (loading && !data) return <LoadingState message="Generating historical reports…" />;
  if (!data) return <ErrorState title="Reports unavailable" message={error} onRetry={() => void load()} />;
  const riskItems = Object.entries(data.risk.riskDistribution).map(([label, value]) => ({ label, value, color: RISK_COLORS[label] || "#837b8a" }));
  const priorityItems = Object.entries(data.alerts.priorityDistribution).map(([label, value]) => ({ label, value, color: PRIORITY_COLORS[label] || "#a969ed" }));
  return <section className="reports-page"><div className="queue-toolbar"><div><p className="eyebrow">Historical intelligence</p><h2>Reports workspace</h2><p>Generate detailed risk, alert, country and rule analysis.</p></div><div className="report-generated"><span>Generated at</span><strong>{generatedAt ? generatedAt.toLocaleString() : "Not yet"}</strong></div></div><form className="alert-filters reports-filters" onSubmit={generate}><label>From<input type="datetime-local" value={draft.from} onChange={(event) => setDraft({ ...draft, from: event.target.value })} /></label><label>To<input type="datetime-local" value={draft.to} onChange={(event) => setDraft({ ...draft, to: event.target.value })} /></label><label>Currency<input maxLength={3} value={draft.currency} onChange={(event) => setDraft({ ...draft, currency: event.target.value.toUpperCase() })} placeholder="INR" /></label><label>Country<input maxLength={2} value={draft.country} onChange={(event) => setDraft({ ...draft, country: event.target.value.toUpperCase() })} placeholder="MM" /></label><label>Risk level<select value={draft.riskLevel} onChange={(event) => setDraft({ ...draft, riskLevel: event.target.value })}><option value="">All risks</option>{["PENDING", "LOW", "MEDIUM", "HIGH", "CRITICAL"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Interval<select value={draft.interval} onChange={(event) => setDraft({ ...draft, interval: event.target.value as "HOUR" | "DAY" })}><option>HOUR</option><option>DAY</option></select></label><div className="filter-actions"><button className="primary-button compact-button" disabled={loading}>{loading ? "Generating…" : "Generate report"}</button><button type="button" className="clear-button" onClick={() => { const empty = emptyDraft(); setDraft(empty); setParams({}); }}>Clear</button></div></form>{error && <div className="background-error">{error}</div>}<div className="applied-filter-summary"><strong>Applied filters</strong><span>{filterSummary(filters)}</span></div><ExportToolbar busy={downloading} onExport={exportFile} /><div className="report-kpis"><Kpi label="Transactions" value={data.risk.totalTransactions} /><Kpi label="Average risk" value={Number(data.risk.averageRiskScore).toFixed(2)} /><Kpi label="High risk" value={data.risk.highRiskTransactions} /><Kpi label="Alerts" value={data.alerts.totalAlerts} /></div><div className="report-chart-grid"><VolumeChart data={data.volume} /><DistributionChart eyebrow="Assessed transactions" title="Risk distribution" centerValue={data.risk.totalTransactions} items={riskItems} /><DistributionChart eyebrow="Alert severity" title="Priority distribution" centerValue={data.alerts.totalAlerts} items={priorityItems} /></div><DistributionTables alerts={data.alerts} /><CountryTable countries={data.countries} /><RuleTable rules={data.rules} /></section>;
}

function ExportToolbar({ busy, onExport }: { busy: string; onExport: (kind: "PDF" | CsvReportType) => void }) { const csv: { label: string; type: CsvReportType }[] = [{ label: "Risk CSV", type: "RISK_SUMMARY" }, { label: "Alerts CSV", type: "ALERT_SUMMARY" }, { label: "Countries CSV", type: "COUNTRY_RISK" }, { label: "Rules CSV", type: "RULE_EFFECTIVENESS" }, { label: "Volume CSV", type: "TRANSACTION_VOLUME" }]; return <div className="export-toolbar"><div><strong>Download filtered report</strong><span>Exports use the filters shown above and are generated by the backend.</span></div><div>{csv.map((item) => <button key={item.type} disabled={Boolean(busy)} onClick={() => onExport(item.type)}>{busy === item.type ? "Preparing…" : item.label}</button>)}<button className="pdf-export" disabled={Boolean(busy)} onClick={() => onExport("PDF")}>{busy === "PDF" ? "Preparing PDF…" : "Management PDF"}</button></div></div>; }
function Kpi({ label, value }: { label: string; value: string | number }) { return <article><span>{label}</span><strong>{value}</strong></article>; }
function DistributionTables({ alerts }: { alerts: DashboardReports["alerts"] }) { return <article className="report-table-card"><header><div><p className="eyebrow">Alert lifecycle</p><h3>Status and decision distribution</h3></div></header><div className="distribution-tables"><MetricList title="Statuses" values={alerts.statusDistribution} /><MetricList title="Decisions" values={alerts.decisionDistribution} /></div></article>; }
function MetricList({ title, values }: { title: string; values: Record<string, number> }) { return <section><strong>{title}</strong>{Object.entries(values).map(([key, value]) => <div key={key}><span>{key.replaceAll("_", " ")}</span><b>{value}</b></div>)}</section>; }
function CountryTable({ countries }: { countries: CountryRisk[] }) { const [sort, setSort] = useState<keyof CountryRisk>("averageRiskScore"); const rows = [...countries].sort((a, b) => Number(b[sort]) - Number(a[sort])); return <article className="report-table-card"><header><div><p className="eyebrow">Route intelligence</p><h3>Country risk</h3></div><span>{countries.length} countries</span></header><div className="report-table-scroll"><table><thead><tr><th>Country</th><Sortable label="Transactions" field="transactionCount" current={sort} set={setSort} /><Sortable label="High risk" field="highRiskTransactionCount" current={sort} set={setSort} /><Sortable label="Alerts" field="alertCount" current={sort} set={setSort} /><Sortable label="Average score" field="averageRiskScore" current={sort} set={setSort} /></tr></thead><tbody>{rows.map((item) => <tr key={item.countryCode}><td><strong>{item.countryCode}</strong></td><td>{item.transactionCount}</td><td>{item.highRiskTransactionCount}</td><td>{item.alertCount}</td><td><span className="table-score">{Number(item.averageRiskScore).toFixed(2)}</span></td></tr>)}</tbody></table></div></article>; }
function RuleTable({ rules }: { rules: RuleEffectiveness[] }) { const [sort, setSort] = useState<keyof RuleEffectiveness>("triggerRate"); const rows = [...rules].sort((a, b) => Number(b[sort]) - Number(a[sort])); return <article className="report-table-card"><header><div><p className="eyebrow">Detection performance</p><h3>Rule effectiveness</h3></div><span>{rules.length} configured rules</span></header><div className="report-table-scroll"><table><thead><tr><th>Rule</th><Sortable label="Evaluated" field="evaluationCount" current={sort} set={setSort} /><Sortable label="Triggered" field="triggerCount" current={sort} set={setSort} /><Sortable label="Trigger rate" field="triggerRate" current={sort} set={setSort} /><Sortable label="Score contribution" field="totalScoreContribution" current={sort} set={setSort} /></tr></thead><tbody>{rows.map((item) => <tr key={item.ruleCode}><td><strong>{item.ruleName}</strong><code>{item.ruleCode}</code></td><td>{item.evaluationCount}</td><td>{item.triggerCount}</td><td><span className="trigger-rate"><i style={{ width: `${Math.min(Number(item.triggerRate), 100)}%` }} /></span><b>{Number(item.triggerRate).toFixed(1)}%</b></td><td>+{item.totalScoreContribution}</td></tr>)}</tbody></table></div></article>; }
function Sortable<T extends string>({ label, field, current, set }: { label: string; field: T; current: T; set: (field: T) => void }) { return <th><button onClick={() => set(field)}>{label}{current === field ? " ↓" : ""}</button></th>; }
function emptyDraft(): Draft { return { from: "", to: "", currency: "", country: "", riskLevel: "", interval: "HOUR" }; }
function draftFrom(params: URLSearchParams): Draft { return { from: params.get("from") || "", to: params.get("to") || "", currency: params.get("currency") || "", country: params.get("country") || "", riskLevel: params.get("riskLevel") || "", interval: (params.get("interval") || "HOUR") as "HOUR" | "DAY" }; }
function filtersFrom(params: URLSearchParams): ReportFilters { const draft = draftFrom(params); return { from: draft.from || undefined, to: draft.to || undefined, currency: draft.currency || undefined, country: draft.country || undefined, riskLevel: (draft.riskLevel || undefined) as RiskLevel | undefined, interval: draft.interval }; }
function filterSummary(filters: ReportFilters) { return [`From ${filters.from ? new Date(filters.from).toLocaleString() : "beginning"}`, `to ${filters.to ? new Date(filters.to).toLocaleString() : "now"}`, filters.currency || "all currencies", filters.country || "all countries", filters.riskLevel || "all risk levels", `${filters.interval || "HOUR"} buckets`].join(" · "); }
function messageOf(caught: unknown) { return caught instanceof ApiError ? caught.message : "Unable to generate report."; }
