import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";

import { ApiError } from "../api/ApiError";
import { getRules, updateRuleStatus } from "../api/rulesApi";
import { useAuth } from "../auth/AuthContext";
import { EmptyState } from "../components/feedback/EmptyState";
import { ErrorState } from "../components/feedback/ErrorState";
import { LoadingState } from "../components/feedback/LoadingState";
import type { MonitoringRule, RuleType } from "../types/rule";

const TYPES: RuleType[] = ["HIGH_AMOUNT", "HIGH_RISK_COUNTRY", "EXCESSIVE_ROUTE_HOPS", "RAPID_TRANSACTIONS", "STRUCTURING", "BLACKLISTED_ACCOUNT"];
export function RuleListPage() {
  const { user } = useAuth(); const admin = user?.role === "ADMIN"; const [params, setParams] = useSearchParams();
  const [rules, setRules] = useState<MonitoringRule[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const type = (params.get("type") || "") as RuleType | ""; const status = params.get("enabled") || ""; const search = params.get("search") || "";
  const load = useCallback(async () => { setLoading(true); try { setRules(await getRules({ type: type || undefined, enabled: status === "" ? undefined : status === "true" })); setError(""); } catch (caught) { setError(messageOf(caught)); } finally { setLoading(false); } }, [type, status]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rules.filter((rule) => !search || `${rule.code} ${rule.name}`.toLowerCase().includes(search.toLowerCase())), [rules, search]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next, { replace: true }); };
  async function toggle(rule: MonitoringRule) { const reason = window.prompt(`Reason for ${rule.enabled ? "disabling" : "enabling"} ${rule.code}:`); if (!reason?.trim()) return; setBusy(rule.id); try { await updateRuleStatus(rule.id, !rule.enabled, reason.trim()); await load(); } catch (caught) { setError(messageOf(caught)); } finally { setBusy(""); } }
  if (loading && rules.length === 0) return <LoadingState message="Loading monitoring rules…" />;
  return <section className="rule-list-page"><div className="queue-toolbar"><div><p className="eyebrow">Rule engine configuration</p><h2>Monitoring rules</h2><p>{admin ? "Configure how future transactions receive risk scores." : "Review the active risk policy in read-only mode."}</p></div>{admin && <Link className="primary-button compact-button" to="/admin/rules/new">Create rule</Link>}</div><div className="rule-warning"><strong>Changes affect future assessments only.</strong><span>Completed transaction assessments retain the rules and scores originally applied.</span></div><div className="alert-filters"><label className="transaction-search">Search<input value={search} onChange={(event) => update("search", event.target.value)} placeholder="Rule code or name" /></label><label>Rule type<select value={type} onChange={(event) => update("type", event.target.value)}><option value="">All types</option>{TYPES.map((value) => <option key={value}>{value}</option>)}</select></label><label>Status<select value={status} onChange={(event) => update("enabled", event.target.value)}><option value="">All rules</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label><button className="clear-button" onClick={() => setParams({}, { replace: true })}>Clear filters</button></div>{error && rules.length === 0 ? <ErrorState message={error} onRetry={() => void load()} /> : <>{error && <div className="background-error">{error}</div>}{visible.length === 0 ? <EmptyState title="No rules match" description="Change or clear the current filters." /> : <RuleTable rules={visible} admin={admin} busy={busy} onToggle={toggle} />}</>}</section>;
}
function RuleTable({ rules, admin, busy, onToggle }: { rules: MonitoringRule[]; admin: boolean; busy: string; onToggle: (rule: MonitoringRule) => void }) { return <div className="alert-table-card"><div className="table-caption"><span>{rules.length} rules</span><span>{admin ? "Administrator controls" : "Read-only policy"}</span></div><div className="alert-table-scroll"><table className="alert-table rule-table"><thead><tr><th>Rule</th><th>Type</th><th>Severity</th><th>Weight</th><th>Status</th><th>Updated</th><th /></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}><td data-label="Rule"><strong>{rule.name}</strong><code>{rule.code}</code></td><td data-label="Type"><span>{humanize(rule.type)}</span></td><td data-label="Severity"><span className={`rule-severity severity-${rule.severity.toLowerCase()}`}>{rule.severity}</span></td><td data-label="Weight"><strong className="rule-weight">+{rule.riskWeight}</strong></td><td data-label="Status"><button className={`status-toggle ${rule.enabled ? "enabled" : ""}`} disabled={!admin || busy === rule.id} onClick={() => onToggle(rule)} title={admin ? "Change rule status" : "Only Administrators can change status"}><i /><span>{rule.enabled ? "Enabled" : "Disabled"}</span></button></td><td data-label="Updated"><time>{formatDate(rule.updatedAt)}</time></td><td><Link className="view-alert-link" to={`/admin/rules/${rule.id}`}>{admin ? "Open rule" : "View rule"} →</Link></td></tr>)}</tbody></table></div></div>; }
function messageOf(caught: unknown) { return caught instanceof ApiError ? caught.message : "Unable to load rules."; }
function humanize(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
