import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";

import { ApiError } from "../api/ApiError";
import { getUsers } from "../api/usersApi";
import { RoleBadge } from "../components/badges/RoleBadge";
import { EmptyState } from "../components/feedback/EmptyState";
import { ErrorState } from "../components/feedback/ErrorState";
import { LoadingState } from "../components/feedback/LoadingState";
import type { UserRole } from "../auth/authTypes";
import type { ManagedUser } from "../types/user";

export function UserListPage() {
  const [params, setParams] = useSearchParams(); const [users, setUsers] = useState<ManagedUser[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const role = (params.get("role") || "") as UserRole | ""; const enabled = params.get("enabled") || ""; const search = params.get("search") || "";
  const load = useCallback(async () => { setLoading(true); try { setUsers(await getUsers({ role: role || undefined, enabled: enabled === "" ? undefined : enabled === "true", search: search || undefined })); setError(""); } catch (caught) { setError(messageOf(caught)); } finally { setLoading(false); } }, [role, enabled, search]); useEffect(() => { void load(); }, [load]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next, { replace: true }); };
  return <section className="user-list-page"><div className="queue-toolbar"><div><p className="eyebrow">Access administration</p><h2>User management</h2><p>Provision analysts and control access without exposing credentials.</p></div><Link className="primary-button compact-button" to="/admin/users/new">Create user</Link></div><div className="user-summary-strip"><article><span>Returned users</span><strong>{users.length}</strong></article><article><span>Enabled</span><strong>{users.filter((user) => user.enabled).length}</strong></article><article><span>Fraud analysts</span><strong>{users.filter((user) => user.role === "FRAUD_ANALYST").length}</strong></article><article><span>Risk analysts</span><strong>{users.filter((user) => user.role === "RISK_ANALYST").length}</strong></article></div><div className="alert-filters"><label className="transaction-search">Search<input value={search} onChange={(event) => update("search", event.target.value)} placeholder="Name, username or email" /></label><label>Role<select value={role} onChange={(event) => update("role", event.target.value)}><option value="">All roles</option>{["ADMIN", "FRAUD_ANALYST", "RISK_ANALYST"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Status<select value={enabled} onChange={(event) => update("enabled", event.target.value)}><option value="">All users</option><option value="true">Enabled</option><option value="false">Disabled</option></select></label><button className="clear-button" onClick={() => setParams({})}>Clear filters</button></div>{loading && users.length === 0 ? <LoadingState message="Loading users…" /> : error && users.length === 0 ? <ErrorState message={error} onRetry={() => void load()} /> : <>{error && <div className="background-error">{error}</div>}{users.length === 0 ? <EmptyState title="No users match" description="Change or clear the current filters." /> : <UserTable users={users} />}</>}</section>;
}
function UserTable({ users }: { users: ManagedUser[] }) { return <div className="alert-table-card"><div className="alert-table-scroll"><table className="alert-table user-table"><thead><tr><th>User</th><th>Username</th><th>Role</th><th>Status</th><th>Created</th><th>Updated</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td data-label="User"><strong>{user.displayName}</strong><span>{user.email}</span></td><td data-label="Username"><code>{user.username}</code></td><td data-label="Role"><RoleBadge role={user.role} /></td><td data-label="Status"><span className={`account-status ${user.enabled ? "enabled" : ""}`}><i />{user.enabled ? "Enabled" : "Disabled"}</span></td><td data-label="Created"><time>{formatDate(user.createdAt)}</time></td><td data-label="Updated"><time>{formatDate(user.updatedAt)}</time></td><td><Link className="view-alert-link" to={`/admin/users/${user.id}`}>Manage →</Link></td></tr>)}</tbody></table></div></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)); }
function messageOf(caught: unknown) { return caught instanceof ApiError ? caught.message : "Unable to load users."; }
