import type { RuleParameters, RuleType } from "../../types/rule";

export function RuleParameterFields({ type, parameters, errors, onChange, disabled }: { type: RuleType; parameters: RuleParameters; errors: Record<string, string>; onChange: (key: string, value: string | number | string[]) => void; disabled: boolean }) {
  const input = (key: string, label: string, kind: "text" | "number" = "number", minimum?: number) => <Field label={label} error={errors[`parameters.${key}`]}><input type={kind} min={minimum} value={String(parameters[key] ?? "")} onChange={(event) => onChange(key, kind === "number" ? Number(event.target.value) : event.target.value.toUpperCase())} disabled={disabled} /></Field>;
  switch (type) {
    case "HIGH_AMOUNT": return <div className="parameter-grid">{input("currency", "Currency", "text")}{input("threshold", "Amount threshold", "number", 0)}</div>;
    case "HIGH_RISK_COUNTRY": return <div className="parameter-grid"><Field label="Country codes" error={errors["parameters.countryCodes"]} hint="Comma-separated ISO codes, for example MM, KP"><input value={Array.isArray(parameters.countryCodes) ? parameters.countryCodes.join(", ") : ""} onChange={(event) => onChange("countryCodes", event.target.value.toUpperCase().split(",").map((value) => value.trim()).filter(Boolean))} disabled={disabled} /></Field><Field label="Route match" error={errors["parameters.match"]}><select value={String(parameters.match || "ANY_ROUTE_HOP")} onChange={(event) => onChange("match", event.target.value)} disabled={disabled}>{["ANY_ROUTE_HOP", "ORIGIN_ONLY", "INTERMEDIARY_ONLY", "DESTINATION_ONLY"].map((value) => <option key={value}>{value}</option>)}</select></Field></div>;
    case "EXCESSIVE_ROUTE_HOPS": return <div className="parameter-grid">{input("maximumHops", "Maximum allowed hops", "number", 2)}</div>;
    case "RAPID_TRANSACTIONS": return <div className="parameter-grid">{input("windowMinutes", "Time window (minutes)", "number", 1)}{input("maximumTransactions", "Maximum transactions", "number", 1)}</div>;
    case "STRUCTURING": return <div className="parameter-grid">{input("currency", "Currency", "text")}{input("windowMinutes", "Time window (minutes)", "number", 1)}{input("minimumTransactionCount", "Minimum transaction count", "number", 2)}{input("individualMaximum", "Individual maximum", "number", 0)}{input("combinedThreshold", "Combined threshold", "number", 0)}<Field label="Group transactions by" error={errors["parameters.groupBy"]}><select value={String(parameters.groupBy || "SENDER")} onChange={(event) => onChange("groupBy", event.target.value)} disabled={disabled}>{["SENDER", "SENDER_AND_RECEIVER", "RECEIVER"].map((value) => <option key={value}>{value}</option>)}</select></Field></div>;
    case "BLACKLISTED_ACCOUNT": return <p className="parameter-empty">This rule reads the managed account watchlist and requires no additional parameters.</p>;
  }
}

function Field({ label, error, hint, children }: { label: string; error?: string; hint?: string; children: React.ReactNode }) { return <label className={error ? "field-invalid" : ""}>{label}{children}{hint && <small>{hint}</small>}{error && <span>{error}</span>}</label>; }
